### ISSUE TITLE
libcap build failure

### ISSUE THREAD

**Issue by periish** [kisslinux/community#1150] opened 2020-08-24 16:48 UTC
libcap fails to build, with an error message of `indent: Command line: unknown parameter "-kr"`.
@a-schaefers

**Comment by a-schaefers** [comment] 2020-08-25 23:56
Can anyone else confirm this is true? I thought I test stuff.

**Comment by dylanaraps** [comment] 2020-08-26 08:16
I can reproduce. 

```sh
-> libcap Starting build
make -C libcap all
make[1]: Entering directory '/tmp/build-1491/libcap/libcap'
=> making cap_names.list.h from /tmp/build-1491/libcap/libcap/../libcap/include/uapi/linux/capability.h
perl -e 'while ($l=<>) { if ($l =~ /^\#define[ \t](CAP[_A-Z]+)[ \t]+([0-9]+)\s+$/) { $tok=$1; $val=$2; $tok =~ tr/A-Z/a-z/; print "{\"$tok\",$val},\n"; } }' /tmp/build-1491/libcap/libcap/../libcap/include/uapi/linux/capability.h | fgrep -v 0x > cap_names.list.h
sed -e 's,@prefix@,/usr,' \
        -e 's,@exec_prefix@,,' \
        -e 's,@libdir@,/usr/lib,' \
        -e 's,@includedir@,/usr/include,' \
        -e 's,@VERSION@,2.42,' \
        -e 's,@deps@,,' \
        libcap.pc.in >libcap.pc
sed -e 's,@prefix@,/usr,' \
        -e 's,@exec_prefix@,,' \
        -e 's,@libdir@,/usr/lib,' \
        -e 's,@includedir@,/usr/include,' \
        -e 's,@VERSION@,2.42,' \
        -e 's,@deps@,,' \
        libpsx.pc.in >libpsx.pc
cc -O2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -I/tmp/build-1491/libcap/libcap/../libcap/include/uapi -I/tmp/build-1491/libcap/libcap/../libcap/include _makenames.c -o _makenames
perl -e 'print "struct __cap_token_s { const char *name; int index; };\n%{\nconst struct __cap_token_s *__cap_lookup_name(const char *, size_t);\n%}\n%%\n"; while ($l = <>) { $l =~ s/[\{\"]//g; $l =~ s/\}.*// ; print $l; }' < cap_names.list.h | gperf --ignore-case --language=ANSI-C --readonly --null-strings --global-table --hash-function-name=__cap_hash_name --lookup-function-name="__cap_lookup_name" -c -t -m20 | indent -kr > _caps_output.gperf
indent: Command line: unknown parameter "-kr"
make[1]: *** [Makefile:59: _caps_output.gperf] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/build-1491/libcap/libcap'
make: *** [Makefile:12: all] Error 2
-> libcap Build failed
```

**Comment by mmatongo** [comment] 2020-08-31 18:11
It builds just fine for me, both v`2.42` and v`2.43`

**Comment by dylanaraps** [comment] 2020-08-31 18:32
Fixed this just now. Patch: ```patch
diff --git a/community/libcap/build b/community/libcap/build
index 101947d..0e9cde9 100755
--- a/community/libcap/build
+++ b/community/libcap/build
@@ -1,5 +1,8 @@
 #!/bin/sh -e

+# Fix build when indent found in path.
+sed -i 's/which indent/false/g' Make.Rules
+
 mk() {
     make \
         GOLANG=no \

~
```

**Comment by cemkeylan** [comment] 2020-08-31 18:33
This is because of baseutils `indent`, if you remove it, it will build just fine. I have had this issue before but forgot to post it here.

**Comment by periish** [comment] 2020-08-31 18:34
I shouldn't have baseutils installed. Hm.

**Comment by cemkeylan** [comment] 2020-08-31 18:36
This can be fixed on the Makefile by doing `make INDENT=true`

**Comment by cemkeylan** [comment] 2020-08-31 18:38
The issue is that it is looking for GNU indent, I didn't look deep into it back then :D

**Comment by mmatongo** [comment] 2020-08-31 20:01
I will make changes to the build file and incorporate the above, the ISP I use for my WiFi isn’t playing well with github right now so I’ll most likely do this tomorrow.

**Closed** 2020-09-01 12:48 UTC
