### ISSUE TITLE
New package AzPainter: testing needed

### ISSUE THREAD

**Issue by Vouivre** [kisslinux/community#153] opened 2019-12-29 22:06 UTC
Hello,

because I have some problems with Gimp and for the moment there is no solution, I'm testing the software AzPainter. With AzPainter I'm experiencing some lags, when I click on a menu, sometimes the software needs 1-2 seconds to react. Could somebody install it and confirm the problem ? 
More details [in this issue](https://github.com/Symbian9/azpainter/issues/75).

Files needed: 

- build:

````
#!/bin/sh -e

./configure \
        --prefix=/usr

make
make DESTDIR="$1" install-strip
````

version:
````
2.1.5 1
````

sources:
````
https://github.com/Symbian9/azpainter/archive/v2.1.5.tar.gz
````

checksums:
````
2ece3a8a8a62e85b08d40bde45f7544f1fb81beff9be61e49f0b8f8e0bd8b022  v2.1.5.tar.gz
````

On my system no other dependecies are needed, if it doesn't work, I'll add the necessary dependencies. For the moment I know the package is not finished.

**Comment by dylanaraps** [comment] 2020-02-15 23:49
It works perfectly for me.

Used this to build:

```
#!/bin/sh -e

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install
```

**Comment by dylanaraps** [comment] 2020-02-24 18:00
Any updates on this? It works fine on my machine. Can you still reproduce?

**Comment by Vouivre** [comment] 2020-02-25 13:32
Hello, sorry for the delay. No, it still doesn't work. I will probably switch my wm from `windowchef` to `sowm` and I will give you an update. But I don't expect it will be better. I have tried with your `build`.

**Comment by Vouivre** [comment] 2020-02-27 06:19
I have switched to `sowm`, but it's not better. So it has nothing to do with the wm. I will install Linux on other computer and I will be able to compare. I think it will be in two or three month. Until then, I don't know where to search: kernel ? Graphical problem ? 

I have to check if graphical acceleration is enableb on my computer. As I understand, I had this problem and I have enabled only for `firefox`. 

I'm still interested by AzPainter, but at the moment it's not usable.

**Comment by a-schaefers** [comment] 2020-03-03 08:26
Is it using GTK? I have seen this problem with GTK before, but not on kiss.

You might trying removing everything related to setting gtk themes, if you have done so, and see if that works around the problem, and might give a hint as to what might be the cause.

**Comment by dylanaraps** [comment] 2020-03-07 10:57
I think it's time we close this one. No one else can reproduce. I think it's best left to upstream. :+1:

**Closed by dylanaraps** 2020-03-07 10:57 UTC
Labels: Help Wanted, Package Issue, Question

**Comment by muevoid** [comment] 2020-04-22 17:02
@dylanaraps Hello! I am having an issue with azpainter where my brushes do not save not sure if this is an issue only with my install or not. If you have time do you think you could possibly test this. Symbian9 has mentioned the issue which has a screencast of the problem.
